---
- name: Install CPUPower systemd service
  ansible.builtin.template:
    src: cpupower.service.j2
    dest: /etc/systemd/system/cpupower.service
    owner: root
    mode: "644"
  register: cpupower

- name: Reload SystemD for CPUPower
  ansible.builtin.command: systemctl daemon-reload
  when: cpupower.changed

- name: Enable CPUPower Service
  ansible.builtin.service:
    name: cpupower
    enabled: true
    state: started
  # If for some reason the system can't control the cpu performance profiles, ignore.
  ignore_errors: true
